logging : 
  level : 
    . : error
    org.springframework : ERROR
    com.oracle.yaml : ERROR
    
    
spring :
  profiles :
    active : "prod"
  main :
    banner-mode : "off"

server :
  email : staphy91@gmail.com
  port : 9000

---

spring :
  profiles : dev

server :
  email : staphy123@oracle.com
  cluster :
    - ip : 127.0.0.1
      path : /dev1
    - ip : 127.0.0.2
      path : /dev2
    - ip : 127.0.0.3
      path : /dev3
      
      
---

spring :
  profiles : prod

server :
  email : staphy234@oracle.com
  cluster :
    - ip : 127.0.0.1
      path : /prod1
    - ip : 127.0.0.2
      path : /prod2
    - ip : 127.0.0.3
      path : /prod3
      
    
